name: aicc

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        profile: [dev, release]
        os: [ubuntu-latest, windows-latest]
        include:
          - profile: dev
            target-dir: debug
          - profile: release
            target-dir: release
          - os: windows-latest
            osname: windows
            extension: .exe
          - os: ubuntu-latest
            osname: linux
            extension:
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: jumbo-hotdog-kaya-mo/aicc
        token: ${{ secrets.REPO_TOKEN }}
    - name: Build "${{ matrix.profile }}"
      run: cargo build --profile ${{ matrix.profile }}
    - name: Test "${{ matrix.profile }}"
      run: cargo test --profile ${{ matrix.profile }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aicc-${{ matrix.osname }}-${{ matrix.profile }}
        path: target/${{ matrix.target-dir }}/aicc${{ matrix.extension }}
